---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Homepage
- type: heading
  label: Docs
- type: document
  path: README.md
  label: README
  match: "**/*"
  read_only: true
- type: directory
  path: docs
  label: Documentation
  create: all
  match: "**/*"
  templates:
  - page
- type: heading
  label: Data
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*.yml"
  new_doc_ext: yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
